# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Animations Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# https://wiki.hyprland.org/Configuring/Animations/

animations {
    enabled = yes
    bezier = overshot, 0.13, 0.99, 0.29, 1.10
    bezier = weird, 0.50, -0.50, 0.50, 1.00
    animation = windowsIn, 1, 4, weird, slide
    animation = windowsOut, 1, 5, default, popin 80%
    animation = border, 1, 5, default
    animation = workspacesIn, 0, 0, default
    animation = workspacesOut, 0, 0, default
    # animation = workspacesIn, 1, 6, weird, slide
    # animation = workspacesOut, 1, 6, weird, slidefade 80%
}
