# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input
device {
    name = ydotoold-virtual-device
    accel_profile = flat
    sensitivity = 0
}

input {
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2
    kb_options = compose:ralt
    sensitivity = -0.91
    accel_profile = flat
}
